services:
  docker-satisfactory:
    container_name: 'docker-satisfactory'
    hostname: 'docker-satisfactory'
    image: 'ghostvr/docker-satisfactory:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory_gamefile:/home/steam/docker/satisfactory_server'
      - './satisfactory_save:/home/steam/.config'
    environment:
      - MAXPLAYERS=16
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
